#!/usr/bin/env node

import Anthropic from "@anthropic-ai/sdk";
import * as fs from "fs";
import * as path from "path";
import * as readline from "readline";
import * as os from "os";
import { execFileSync } from "child_process";

const anthropic = new Anthropic();

// Progress tracking
interface Progress {
  userName: string;
  currentModule: number;
  currentLesson: number;
  completed: string[];
  quizScores: Record<string, number>;
  startedAt: string;
  checkpoints: Record<string, CheckpointData>;
}

interface CheckpointData {
  completedAt: string;
  responses: Record<string, string>;
  score?: number;
  feedback?: string;
}

const PROGRESS_DIR = path.join(os.homedir(), ".oversite-training");
const PROGRESS_FILE = path.join(PROGRESS_DIR, "progress.json");
const REPO_PATH = "/tmp/oversite-onboarding";

function loadProgress(): Progress {
  try {
    if (fs.existsSync(PROGRESS_FILE)) {
      return JSON.parse(fs.readFileSync(PROGRESS_FILE, "utf-8"));
    }
  } catch (e) {
    // Ignore
  }
  return {
    userName: "",
    currentModule: 1,
    currentLesson: 1,
    completed: [],
    quizScores: {},
    startedAt: new Date().toISOString(),
    checkpoints: {},
  };
}

function saveProgress(progress: Progress) {
  if (!fs.existsSync(PROGRESS_DIR)) {
    fs.mkdirSync(PROGRESS_DIR, { recursive: true });
  }
  fs.writeFileSync(PROGRESS_FILE, JSON.stringify(progress, null, 2));
}

// Save checkpoint to GitHub
function saveCheckpointToGitHub(
  userName: string,
  moduleNum: number,
  checkpoint: CheckpointData
) {
  const sanitizedName = userName.toLowerCase().replace(/[^a-z0-9]/g, "-");
  const checkpointDir = path.join(REPO_PATH, "students", sanitizedName);
  const checkpointFile = path.join(
    checkpointDir,
    `module-${moduleNum}-checkpoint.md`
  );

  // Create directory
  if (!fs.existsSync(checkpointDir)) {
    fs.mkdirSync(checkpointDir, { recursive: true });
  }

  // Generate markdown
  const md = `# Module ${moduleNum} Checkpoint - ${userName}

**Completed:** ${checkpoint.completedAt}
${checkpoint.score ? `**Score:** ${checkpoint.score}/100` : ""}

## Responses

${Object.entries(checkpoint.responses)
  .map(([q, a]) => `### ${q}\n\n${a}`)
  .join("\n\n")}

${checkpoint.feedback ? `## Instructor Feedback\n\n${checkpoint.feedback}` : ""}

---
*Generated by OverSite Training System*
`;

  fs.writeFileSync(checkpointFile, md);

  // Commit and push to GitHub using execFileSync (safer than execSync)
  try {
    execFileSync("git", ["add", "students/"], { cwd: REPO_PATH, stdio: "pipe" });
    execFileSync(
      "git",
      ["commit", "-m", `Checkpoint: ${userName} completed Module ${moduleNum}`],
      { cwd: REPO_PATH, stdio: "pipe" }
    );
    execFileSync("git", ["push", "origin", "main"], { cwd: REPO_PATH, stdio: "pipe" });
    return true;
  } catch (e) {
    console.error("Failed to push to GitHub. Saved locally.");
    return false;
  }
}

// Load curriculum
function loadCurriculum(): string {
  const curriculumDir = path.join(__dirname, "..", "curriculum");
  let content = "";

  const walkDir = (dir: string) => {
    if (!fs.existsSync(dir)) return;
    const files = fs.readdirSync(dir);
    for (const file of files.sort()) {
      const filePath = path.join(dir, file);
      const stat = fs.statSync(filePath);
      if (stat.isDirectory()) {
        walkDir(filePath);
      } else if (file.endsWith(".md")) {
        content += `\n\n---\n# FILE: ${file}\n\n`;
        content += fs.readFileSync(filePath, "utf-8");
      }
    }
  };

  walkDir(curriculumDir);
  return content;
}

// Load knowledge base
function loadKnowledgeBase(): string {
  const kbDir = path.join(__dirname, "..", "knowledge-base");
  let content = "";

  if (fs.existsSync(kbDir)) {
    const files = fs.readdirSync(kbDir).filter((f) => f.endsWith(".md"));
    for (const file of files) {
      content += `\n\n---\n# ${file}\n\n`;
      content += fs.readFileSync(path.join(kbDir, file), "utf-8");
    }
  }

  return content;
}

function buildSystemPrompt(userName: string): string {
  return `You are the OverSite Training System. You're training ${userName || "an engineer"} on the OverSite codebase.

# CURRICULUM
${loadCurriculum()}

# KNOWLEDGE BASE
${loadKnowledgeBase()}

# YOUR ROLE

You are a Socratic instructor who:
1. Follows the curriculum in order
2. Uses ASCII visualizations for every concept
3. Probes the student to THINK, not just recall
4. Asks creative "what if" questions
5. Celebrates good thinking, gently corrects misconceptions

# TEACHING PHILOSOPHY

**Don't just lecture. Make them think.**

Bad: "The 4 layers are Perception, Action, Observation, Agent."
Good: "Before I tell you the architecture, what layers would YOU design if you were building an AI copilot for glasses? Think about what needs to happen..."

**Use Socratic questioning:**
- "Why do you think they chose that approach?"
- "What would break if we removed this layer?"
- "How would you solve this differently?"
- "What's the tradeoff here?"

**Probe for deep understanding:**
- Don't accept surface-level answers
- Ask follow-up questions
- Challenge assumptions
- Explore edge cases together

# CREATIVE THINKING PROMPTS

At the end of each concept, ask ONE of these:
1. "If you were redesigning this, what would you change?"
2. "What's the biggest weakness of this approach?"
3. "How would this break at 10x scale?"
4. "What would this look like in [different industry]?"
5. "If you had to explain this to a 5-year-old, what would you say?"

# CHECKPOINT SYSTEM

At the end of each module, run a checkpoint:
1. Ask knowledge questions (verify recall)
2. Ask creative questions (verify understanding)
3. Ask reflection questions (what surprised them, what's still unclear)
4. Collect their responses
5. Tell them their checkpoint is being saved to GitHub

When the student says "checkpoint" or finishes a module, run the checkpoint sequence.

# VISUALIZATION RULES

ALWAYS use ASCII diagrams. Never explain architecture without a visual.

# PERSONALIZATION

Address the student by name: ${userName || "friend"}
Remember their previous answers and refer back to them.
Adapt your pace to their understanding level.

Remember: Your goal is for ${userName || "this engineer"} to DEEPLY UNDERSTAND the system, not just memorize facts. They should be able to ship features AND explain WHY the system is designed this way.`;
}

interface Message {
  role: "user" | "assistant";
  content: string;
}

const conversationHistory: Message[] = [];
let progress = loadProgress();
let systemPrompt = buildSystemPrompt(progress.userName);

async function chat(userMessage: string): Promise<string> {
  const lower = userMessage.toLowerCase().trim();

  // Handle special commands
  if (lower === "progress") {
    return formatProgress();
  }

  if (lower === "reset") {
    const name = progress.userName;
    progress = {
      userName: name,
      currentModule: 1,
      currentLesson: 1,
      completed: [],
      quizScores: {},
      startedAt: new Date().toISOString(),
      checkpoints: {},
    };
    saveProgress(progress);
    return "Progress reset. Starting from Module 1.1.";
  }

  // Add context
  const contextMessage = `[SYSTEM: Student "${progress.userName}" is on Module ${progress.currentModule}, Lesson ${progress.currentLesson}. Completed: ${progress.completed.length} lessons.]

${userMessage}`;

  conversationHistory.push({
    role: "user",
    content: contextMessage,
  });

  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 8096,
    system: systemPrompt,
    messages: conversationHistory,
  });

  const assistantMessage =
    response.content[0].type === "text" ? response.content[0].text : "";

  conversationHistory.push({
    role: "assistant",
    content: assistantMessage,
  });

  // Track progress
  if (lower === "next") {
    const lessonKey = `${progress.currentModule}.${progress.currentLesson}`;
    if (!progress.completed.includes(lessonKey)) {
      progress.completed.push(lessonKey);
    }
    progress.currentLesson++;
    if (progress.currentLesson > 3) {
      progress.currentModule++;
      progress.currentLesson = 1;
    }
    saveProgress(progress);
  }

  if (lower === "back" && (progress.currentLesson > 1 || progress.currentModule > 1)) {
    progress.currentLesson--;
    if (progress.currentLesson < 1) {
      progress.currentModule--;
      progress.currentLesson = 3;
    }
    saveProgress(progress);
  }

  return assistantMessage;
}

function formatProgress(): string {
  const totalLessons = 18;
  const pct = Math.round((progress.completed.length / totalLessons) * 100);

  return `
╔════════════════════════════════════════════════════════════╗
║           ${progress.userName}'s TRAINING PROGRESS
╠════════════════════════════════════════════════════════════╣
║                                                            ║
║  Current: Module ${progress.currentModule}, Lesson ${progress.currentLesson}
║  Completed: ${progress.completed.length}/${totalLessons} lessons (${pct}%)
║                                                            ║
║  [${"█".repeat(Math.floor(pct / 5))}${"░".repeat(20 - Math.floor(pct / 5))}]
║                                                            ║
║  Started: ${progress.startedAt.split("T")[0]}
║  Checkpoints saved: ${Object.keys(progress.checkpoints).length}
║                                                            ║
╚════════════════════════════════════════════════════════════╝

Commands:
  next       - Continue to next lesson
  back       - Go to previous lesson
  checkpoint - Save module progress to GitHub
  progress   - Show this screen
  reset      - Start over
`;
}

async function askForName(rl: readline.Interface): Promise<string> {
  return new Promise((resolve) => {
    rl.question("\nWhat's your name? ", (name) => {
      resolve(name.trim());
    });
  });
}

async function main() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║     ██████╗ ██╗   ██╗███████╗██████╗ ███████╗██╗████████╗    ║
║    ██╔═══██╗██║   ██║██╔════╝██╔══██╗██╔════╝██║╚══██╔══╝    ║
║    ██║   ██║██║   ██║█████╗  ██████╔╝███████╗██║   ██║       ║
║    ██║   ██║╚██╗ ██╔╝██╔══╝  ██╔══██╗╚════██║██║   ██║       ║
║    ╚██████╔╝ ╚████╔╝ ███████╗██║  ██║███████║██║   ██║       ║
║     ╚═════╝   ╚═══╝  ╚══════╝╚═╝  ╚═╝╚══════╝╚═╝   ╚═╝       ║
║                                                               ║
║                   ENGINEER TRAINING SYSTEM                    ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
`);

  // Get or confirm name
  if (!progress.userName) {
    const name = await askForName(rl);
    progress.userName = name;
    saveProgress(progress);
    systemPrompt = buildSystemPrompt(name);
    console.log(`\nWelcome, ${name}! Let's get you shipping features.\n`);
  } else {
    console.log(`\nWelcome back, ${progress.userName}!\n`);
  }

  console.log(formatProgress());
  console.log("\nType 'start' to begin training.\n");

  const prompt = () => {
    rl.question(`${progress.userName}: `, async (input) => {
      const trimmed = input.trim();

      if (["quit", "exit"].includes(trimmed.toLowerCase())) {
        console.log(`\nProgress saved. See you next time, ${progress.userName}!\n`);
        rl.close();
        return;
      }

      if (!trimmed) {
        prompt();
        return;
      }

      try {
        console.log("\n");
        const response = await chat(trimmed);
        console.log(`${response}\n`);
      } catch (error) {
        console.error("Error:", error);
      }

      prompt();
    });
  };

  prompt();
}

main().catch(console.error);
